#!/usr/bin/env bash

ssm_run() {
  : '
  Run ssm parameter command
  '

  # Set required parameters
  local command
  local instance_id
  # Other args used throughout
  local parameter_arg
  local command_out
  local command_run
  local command_id

  # Get input arguments
  while [ $# -gt 0 ]; do
          case "$1" in
              --command)
                  command="$2"
                  shift 2
              ;;
              --instance-id)
                  instance_id="$2"
                  shift 2
              ;;
          esac
          shift
  done

  # Check --instance-id is defined
  if [[ -z "${instance_id}" ]]; then
    echo "Error, must specify --instance-id for ssm_run function"
    return 1
  fi

  # Switch command to /dev/stdin if not defined in parameter above
  if [[ -z "${command}" ]];then
    command="$(</dev/stdin)"
  fi

  # Now jq'ise the parameter arguments
  # Credit: https://stackoverflow.com/a/38862221/6946787
  parameter_arg="$(jq --raw-output \
                      --arg "key" "commands" \
                      --arg "command_prefix" "su - \"ec2-user\"" \
                      --arg "command_value" "${command}" \
                      '.[$key]=[$command_prefix + " -c " + "\($command_value | tojson)"]' <<< '{}' \
                  )"

  # Now send through run shell script command to instance
  command_out="$(aws ssm send-command \
                  --output json \
                  --document-name "AWS-RunShellScript" \
                  --targets "Key=InstanceIds,Values=${instance_id}" \
                  --parameters "${parameter_arg}" \
                )"

  # Write back command to user
  command_run="$(echo "${command_out}" | \
                 jq --raw-output \
	                '.Command.Parameters.commands[0]'
               )"

  # Get command ID
  command_id="$(echo "${command_out}" |
                 jq --raw-output \
	                '.Command.CommandId'
               )"

  echo "Running the following command on \"${instance_id}\"" 1>&2
  echo "${command_run}" 1>&2

  echo "Query command status with 'aws ssm list-commands --instance-id=\"${instance_id}\" --command-id=\"${command_id}\"'" 1>&2
}
