---
name: conda

title: -conda

subcommands:
  activate:
    summary: |
      Activate a conda environment.
    parameters:
      - name: env_name_or_prefix
        completion:
          command_string: |
            conda env list --json | \
            jq --raw-output \
              '
                .envs | 
                map(split("/")[-1]) | 
                .[]
              '